services:
  nestjs-backend:
    image: theanh2906/nestjs-backend
    container_name: nestjs-backend
    network_mode: host
    dns:
      - 8.8.8.8
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      # Add environment variables if necessary
      NODE_ENV: prod
    restart: always
    volumes:
      - obsidian-notes:/data/obsidian-notes
      - firebase:/data/firebase
#    depends_on:
#      - rabbitmq
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    network_mode: host
#    ports:
#      - '5672:5672'
#      - '15672:15672'
#      - '15674:15674'
#    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: admin
#    restart: always
#    # Enable STOMP plugin
#    command: >
#      bash -c "
#        rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_web_stomp rabbitmq_stomp &&
#        rabbitmq-server
#      "

volumes:
  obsidian-notes:
    driver: local
    driver_opts:
      type: none
      device: /home/benna/backup_data/obsidian_notes
      o: bind
  firebase:
    driver: local
    driver_opts:
      type: none
      device: /home/benna/backup_data/firebase
      o: bind